version: "3.7"
services:
  app:
    build:
      args:
        user: dev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php-laravel
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./www:/var/www
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: laravel
      MYSQL_USER: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql    
    networks:
      - laravel

  web:
    image: nginx:1.17-alpine
    container_name: laravel-web
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./www:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel

networks:
  laravel:
    driver: bridge